return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.bars-and-lines/lualine-nvim" },
  --{ import = "astrocommunity.editing-support/auto-save-nvim" },
  --{ import = "astrocommunity.editing-support/cloak-nvim" },
  --{ import = "astrocommunity.editing-support/cutlass-nvim" },
  --{ import = "astrocommunity.editing-support/rainbow-delimiters-nvim" },
  --{ import = "astrocommunity.editing-support/todo-comments-nvim" },
  --{ import = "astrocommunity.editing-support/undotree" },
  --{ import = "astrocommunity.editing-support/wildfire-nvim" },
  --{ import = "astrocommunity.editing-support/yanky.nvim" },
  --{ import = "astrocommunity.debugging.persistent-breakpoints-nvim" },
  --{ import = "astrocommunity.debugging.telescope-dap-nvim" },
  { import = "astrocommunity.file-explorer/oil-nvim" },
  { import = "astrocommunity.git/git-blame-nvim" },
  { import = "astrocommunity.lsp/lsp-signature-nvim" },
  --{ import = "astrocommunity.motion/harpoon" },
  { import = "astrocommunity.motion/nvim-surround" },
  --{ import = "astrocommunity.pack.ansible" },
  --{ import = "astrocommunity.pack.proto" },
  { import = "astrocommunity.pack.rust" },
  --{ import = "astrocommunity.pack.typescript" },
  --{ import = "astrocommunity.pack.typescript-deno" },
  { import = "astrocommunity.pack.typescript-all-in-one" },
  --{ import = "astrocommunity.programming-language-support.nvim-jqx" },
  --{ import = "astrocommunity.recipes.telescope-nvchad-theme" },
  -- { import = "astrocommunity.utility/noice-nvim" },
  { import = "astrocommunity.utility/telescope-lazy-nvim" },
  -- { import = "astrocommunity.pack.java" },
}
