#!/bin/sh

BOARD_DTS="{{board_dts}}"
BOARD="{{board}}"
DTS="{{DIR}}/linux/arch/arm/boot/dts/${BOARD_DTS}.dts"
DTB="{{VAR}}/${BOARD}.dtb"
#dtc -O dtb -o "${DTB}" "${DTS}"

SRC="{{DIR}}/linux/arch/arm/boot/dts/${BOARD_DTS}.dtb"
cp "${SRC}" "${DTB}"
