#!/bin/sh
set -e

BOARD="{{board_uboot}}"
BIN="{{board}}.bin"
KWB="{{board}}.kwb"
UBOOT_DIR="{{DIR}}/uboot"
VAR="{{VAR}}"
export CROSS_COMPILE="{{cc_uboot|default(cc)}}"

cd "${UBOOT_DIR}" || exit
#make distclean
make "${BOARD}_config"
make u-boot.kwb

cp u-boot.bin "${VAR}/${BIN}"
ln -sf "${VAR}/${BIN}" "${VAR}/uboot.bin"
cp u-boot.kwb "${VAR}/${KWB}"
ln -sf "${VAR}/${KWB}" "${VAR}/uboot.kwb"
