#!/bin/bash
[ -z "$REPO" ] && REPO="{{REPO_DIR}}"
[ -z "$VIRTUALENV" ] && VIRTUALENV="$NAME"
set -e

source `whereis virtualenvwrapper.sh | awk '{print $2}'`/virtualenvwrapper.sh || true
mkvirtualenv -p /usr/bin/python2 "$VIRTUALENV"
cd $REPO
workon "$VIRTUALENV"
pip install -r requirements.txt
