---
- hosts: all
  vars:
    REPO: https://github.com/cgzones/apt-cacher-rs

    # `RUST: True` is intentionally NOT used. Its install step symlinks
    # target/release/<bin> -> $GLOBAL_BINS_DIR, but that symlink target lives
    # under DIR (mode 0770, root-owned) which this daemon -- which refuses to
    # run as root (main.rs:791) -- cannot traverse. The hand-written install.sh
    # below `cp --remove-destination`s the artifact into /usr/local/bin as a
    # real, world-executable file instead.

    # Build deps for the default feature set (`mmap`, `tls_rustls`, `sendfile`):
    #   - aws-lc-sys (rustls' default crypto provider) builds via cmake + cc/perl
    #   - sqlx sqlite (libsqlite3-sys); ca-certificates for rustls native roots
    PKGS:
      - build-essential
      - cmake
      - perl
      - pkg-config
      - libsqlite3-dev
      - ca-certificates

    # Triggers env.export (files/_env) so $DIR / $GLOBAL_BINS_DIR are available
    # to install.sh at runtime rather than baked in as Jinja.
    ENV: True

    # Dedicated daemon user/group: the binary exits if euid == 0 unless
    # --permit-running-daemon-as-root is passed (which we do not do). The
    # unit's User=/Group= are set directly in SYSTEMD_SERVICES below (compfuzor's
    # SYSTEMD_USER var only normalises a run-as hint, it does not emit the
    # directive). The user/group itself is created by the pre-task.
    SYSTEMD_USER: apt-cacher-rs

    # All daemon state lives under {{VAR}} (== StateDirectory below, which
    # systemd chowns to the apt-cacher-rs user on start): the SQLite metadata
    # DB directly, and the .deb cache under a declared cache/ subdir.
    VAR_DIRS:
      - cache

    ETC_FILES:
      - name: apt-cacher-rs.conf
        content: |
          # Generated by compfuzor/apt-cacher-rs.src.pb
          # man: apt-cacher-rs(8)   upstream: https://github.com/cgzones/apt-cacher-rs
          # Full option reference: debian/apt-cacher-rs.conf in the source tree.
          #
          # The proxy listens on :3142. Point apt clients at it via
          #   /etc/apt/apt.conf.d/30proxy:
          #     Acquire::http::Proxy "http://<host>:3142/";
          # https_upgrade_mode (default 'Auto') fetches from upstream over TLS,
          # so clients may keep plain http:// URLs and still benefit from cache.

          # All daemon state under {{VAR}} (== the unit's StateDirectory, which
          # systemd chowns to the apt-cacher-rs user on start): SQLite metadata
          # DB directly, .deb cache under the cache/ subdir declared via VAR_DIRS.
          cache_directory = '{{VAR}}/cache'
          database_path   = '{{VAR}}/apt-cacher-rs.db'

          # Reference-based pruning reclaims packages absent from the current
          # Release set; disk_quota is a hard backstop (suffixes k/Ki/M/Mi/G/Gi).
          disk_quota = '5Gi'

          allowed_mirrors = [
            '*.debian.org', 'deb.debian.org', 'security.debian.org',
            '*.ubuntu.com', 'archive.ubuntu.com', 'security.ubuntu.com',
            'apt.llvm.org', 'download.vscodium.com',
          ]
          allowed_proxy_clients = [ '127.0.0.1', '::1', '192.168.0.0/16', '10.0.0.0/8', '172.16.0.0/12' ]
          allowed_webif_clients = [ '127.0.0.1', '::1', '192.168.0.0/16', '10.0.0.0/8', '172.16.0.0/12' ]

          # bind_port          = 3142     (default)
          # https_upgrade_mode = 'Auto'   (default)
      - name: 30proxy
        content: |
          # Client snippet -- install on apt clients (including this host) to
          # route through the proxy:
          #   cp {{DIR}}/etc/30proxy /etc/apt/apt.conf.d/30proxy
          # Edit the host below if this runs on another machine.
          Acquire::http::Proxy "http://127.0.0.1:3142/";

    # One real install bin (build + copy). `basedir: repo` cds into $DIR/repo,
    # which fs_repo.tasks always symlinks to the actual checkout (clone or
    # archive copy). `become: true` because the copy targets /usr/local/bin.
    BINS:
      - name: install.sh
        basedir: repo
        run: true
        become: true
        content: |
          # Cargo.toml edition = "2024": needs Rust >= 1.85 (rustup default).
          cargo build --release --locked
          # Real copy (not a symlink) so the non-root daemon can exec it
          # without traversing the 0770 root-owned build dir.
          cp -f --remove-destination target/release/apt-cacher-rs "$GLOBAL_BINS_DIR/apt-cacher-rs"
          chmod 0755 "$GLOBAL_BINS_DIR/apt-cacher-rs"

    # --- newer compfuzor systemd subsystem (tasks/compfuzor/vars_systemd_unit.tasks) ---
    SYSTEMD_UNITS:
      Description: apt-cacher-rs -- caching HTTP proxy for Debian-style repositories
      Documentation: https://github.com/cgzones/apt-cacher-rs
      After: network-online.target nss-lookup.target
      Wants: network-online.target
    SYSTEMD_SERVICES:
      Type: simple
      User: apt-cacher-rs
      Group: apt-cacher-rs
      ExecStart: "{{GLOBAL_BINS_DIR}}/apt-cacher-rs --config-file {{ETC}}/apt-cacher-rs.conf --skip-log-timestamp"
      Restart: on-failure
      RestartSec: "3"
      # {{VAR}} (== {{NAME}} under /var/lib): systemd creates + chowns it to
      # SYSTEMD_USER/Group on start. Holds the DB and the cache/ subdir
      # (declared to compfuzor via VAR_DIRS above).
      StateDirectory: "{{NAME}}"
      LimitNOFILE: "16384"
      # Hardening, ported from the upstream debian/apt-cacher-rs.service.
      NoNewPrivileges: "yes"
      CapabilityBoundingSet: ""
      PrivateTmp: "yes"
      PrivateDevices: "yes"
      ProtectSystem: strict
      ProtectHome: "yes"
      ProtectClock: "yes"
      ProtectHostname: "yes"
      ProtectControlGroups: "yes"
      ProtectKernelTunables: "yes"
      ProtectKernelModules: "yes"
      ProtectKernelLogs: "yes"
      ProtectProc: invisible
      RestrictNamespaces: "yes"
      RestrictRealtime: "yes"
      RestrictSUIDSGID: "yes"
      LockPersonality: "yes"
      MemoryDenyWriteExecute: "yes"
      RemoveIPC: "yes"
      UMask: "0027"
    SYSTEMD_INSTALLS:
      WantedBy: multi-user.target

    README: |
      # apt-cacher-rs

      A caching HTTP proxy for apt/deb repositories — the memory-safe Rust
      successor to apt-cacher-ng. Built from source ({{REPO}}) and run as a
      hardened, non-root system service on port 3142.

      ## Run / iterate

          # full install (needs passwordless sudo for the user task + /usr/local/bin)
          ansible-playbook -i 'localhost,' -c local {{NAME}}.src.pb

          # iterate without side effects (no apt, no clone, no build, no enable)
          ansible-playbook -i 'localhost,' -c local {{NAME}}.src.pb \
            -e PKGS_BYPASS=True -e APT_BYPASS=True -e REPO_BYPASS=True \
            -e BINS_RUN_BYPASS=True -e SYSTEMD_THUNK_BYPASS=True

      Build requirement: Rust >= 1.85 (Cargo.toml `edition = "2024"`).

      ## Point apt clients at the proxy

      On any host that should use the cache (including this one, once the
      service is up):

          # echo 'Acquire::http::Proxy "http://<this-host>:3142/";' \
          #   > /etc/apt/apt.conf.d/30proxy

      A ready-made snippet is at `{{DIR}}/etc/30proxy` (bound to 127.0.0.1 —
      edit the host for remote clients). HTTPS upstreams are fetched over TLS
      by the proxy (`https_upgrade_mode`, default 'Auto'), so clients may keep
      plain http:// source URLs and still get cached, verified packages.

      ## Locations

      | what        | where                                                |
      |------------|------------------------------------------------------|
      | binary     | /usr/local/bin/apt-cacher-rs (real file, not symlink)|
      | config     | {{ETC}}/apt-cacher-rs.conf                           |
      | state (VAR)| {{VAR}} (systemd StateDirectory, auto-chowned)       |
      | cache      | {{VAR}}/cache (declared via VAR_DIRS)                |
      | database   | {{VAR}}/apt-cacher-rs.db                             |
      | service    | {{NAME}}.service (system scope)                      |
      | daemon user| apt-cacher-rs (system user, nologin)                 |
      | web UI     | http://<host>:3142/   (and /logs)                    |

      ## Tuning

      Edit `{{ETC}}/apt-cacher-rs.conf` and `systemctl restart {{NAME}}`.
      Notable knobs: `disk_quota` (hard cap; reference-based pruning reclaims
      packages absent from the current Release set independently), `allowed_mirrors`
      (empty by default in upstream — this playbook seeds Debian/Ubuntu/LLVM),
      `allowed_proxy_clients` / `allowed_webif_clients` (client ACLs). Full
      option reference: `debian/apt-cacher-rs.conf` in the source tree, or
      `man apt-cacher-rs(8)`.
  tasks:
    - name: Create apt-cacher-rs system user/group
      user:
        name: apt-cacher-rs
        group: apt-cacher-rs
        system: true
        create_home: false
        home: /nonexistent
        shell: /usr/sbin/nologin
      become: true
    - import_tasks: tasks/compfuzor.includes
