---
- hosts: all
  vars:
    TYPE: kernel-aspm
    INSTANCE: main
    ETC_FILES:
      - name: kernel-aspm.conf
        content: |
          options pcie_aspm policy=superpowersave
    LINKS:
      - src: "{{ETC}}/kernel-aspm.conf"
        dest: "/etc/modprobe.d/kernel-aspm.conf"

  tasks:
    - include: tasks/compfuzor.includes type=etc
