#! /bin/sh

# help via https://github.com/filakhtov/kernel-postinst-d/blob/master/93-bootctl-entry

set -e

if type systemd-detect-virt >/dev/null 2>&1 &&
   systemd-detect-virt --quiet --container; then
	exit 0
fi

version=$1
baseVersion=${version%%-*}

writeEntry(){
	cat <<EOF
title Debian Linux
linux /vmlinuz-${version}
initrd /initrd.img-${version}
options $(cat /boot/loader/linux-options)
EOF
}

set -- $DEB_MAINT_PARAMS
mode="${1#\'}"
mode="${mode%\'}"
case $0:$mode in
    # Only run on postinst configure and postrm remove, to avoid wasting
    # time by calling update-grub multiple times on upgrade and removal.
    # Also run if we have no DEB_MAINT_PARAMS, in order to work with old
    # kernel packages.
    */postinst.d/*:|*/postinst.d/*:configure|*/postrm.d/*:|*/postrm.d/*:remove)
	
	writeEntry > /boot/loader/entries/linux.conf
	;;
esac

exit 0

