# status.sh — run all registered status reporters in order.
#
# Generated by the status subsystem. The reporter list below is baked in at
# render time from the STATUSES fact -- not globbed -- so ordering is deliberate:
#   - gen_kernel appends status-sysctl.ts / status-modules.ts / status-sysfs.ts
#     for active kernel leaves;
#   - the status subsystem appends status-dirs.sh when STATUS_DIRS is set.
#
# Each reporter runs with "$@" passed through, under a section header. Exit
# codes per reporter: 0 clean, 1 drift, 2 not-applicable (skipped silently).
# status.sh exits 1 if any reporter drifts, 0 if all are clean (or skipped).
#
# This is a compfuzor _bin body: files/_bin supplies the shebang,
# `set -euo pipefail`, env loading, and option restoration.

# ordered reporters, baked in at render time from STATUSES
REPORTERS=(
{% for r in STATUSES | default([]) %}  {{ r }}
{% endfor %})

overall=0
for r in "${REPORTERS[@]}"; do
  script="$DIR/bin/$r"
  [ -x "$script" ] || continue
  printf '\n=== %s ===\n' "$r"
  code=0
  "$script" "$@" || code=$?
  case "$code" in
    0|2) ;;            # clean, or not-applicable -> skip silently
    *)   overall=1 ;;  # drift (1) or unexpected error -> needs attention
  esac
done

exit "$overall"
