#!/bin/bash
set -e

{% include "_bin.header" %}

{% if item.comments is defined %}#{{item.comments}}{% endif %}

{% for var in item.vars|default([]) %}
export {{var}}="{{ '${' }}{{ var }}-{{ hostvars[inventory_hostname][var]|default(vars[var]) }}{{ '}'}}"
{% endfor %}
{% if item.basedir|default(True) == True %}
cd "${DIR}"
{% elif item.basedir|default(True) == False %}
{% elif item.basedir[0] == "/" or item.basedir[0] == "~" %}
cd {{item.basedir}}
{% else %}
cd {{DIR}}/{{item.basedir}}
{% endif %}

{{ item.early|default([])|arrayitize|join("\n") }}
{{ item.generated|default([], True)|arrayitize|join("\n") if item.generatedAt|def == "early" else omit }}
{{ item.content|default([])|arrayitize|join("\n") }}
{{ item.exec|default([])|arrayitize|join("\n") }}
{{ item.execs|default([], True)|arrayitize|join("\n") }}
{{ item.generated|default([], True)|arrayitize|join("\n") if item.generatedAt|def != "early" else omit }}
{{ item.late|default([])|arrayitize|join("\n") }}

{% include "_bin.footer" %}
