---
hosts:
- host: yoyodyne.com
  user: joe
  port: 22
  monitor: 10060
  key: id_rsa_yoyodyne
  local:
    #localhost will gain access to these destinations
    "1222": "localhost:22"
  remote:
    #farhost will gain access to these destinations
    "1333": "localhost:22"
