#!/bin/sh
set -e
[ ! -d "$SYSLINUX_MNT_FAT" ] && exit 1

export SYSLINUX_DIR="${SYSLINUX_MNT_FAT}/.{{NAME}}"

# copy in syslinux config, assets
cp -n "{{ETC}}/syslinux.cfg" "$SYSLINUX_DIR"
cp -r "{{LIB}}/mbr/mbr.bin"* "$SYSLINUX_DIR"
cp -r "{{LIB}}/mbr/gptmbr.bin"* "$SYSLINUX_DIR"
cp -r "{{LIB}}/modules/bios/"* "$SYSLINUX_DIR"

# install into mbr
syslinux "$SYSLINUX_DEV_FAT" -d ".{{NAME}}" {{syslinux_opts|default('', true)}}

# finish copy; unmount.
#umount "$SYSLINUX_MNT_FAT"
