#!/bin/sh
set -e
[ ! -d "$SYSLINUX_MNT_FAT" ] && exit 1

export SYSLINUX_DIR="${SYSLINUX_MNT_FAT}/syslinux"
[ ! -d "$SYSLINUX_DIR" ] && mkdir $SYSLINUX_DIR

# copy in syslinux config, assets
cp -n "{{VAR}}/syslinux.cfg" "$SYSLINUX_DIR"
cp -r "{{LIB}}/mbr/mbr.bin"* "$SYSLINUX_DIR"
cp -r "{{LIB}}/modules/bios/"* "$SYSLINUX_DIR"

# install into mbr
syslinux "$SYSLINUX_DEV_FAT" -d $SYSLINUX_DIR {{syslinux_opts|default('', true)}}


# finish copy; unmount.
umount "$SYSLINUX_MNT_FAT"
