#!/bin/sh
set -e

VAR="{{VAR}}"
ETC="{{ETC}}"
DIST="{{DIST}}"
BOARD="{{board}}"
BOARD_DTS="{{board_dts}}"
SRC="{{board_dts_src}}"
LINUX="{{linux_dir}}"

# source link maintenance
# link dts if we have none locally
[ ! -e $ETC/dts/$BOARD.dts ] && ln -s $SRC.dts $ETC/dts/$BOARD.dts
# copy our dts if we have a real file
[ -f $ETC/dts/$BOARD.dtb ] && rm $SRC.dts && ln -s $SRC $ETC/dts/$BOARD

# build dtb
(cd $LINUX; make ARCH={{arch|lower}} CROSS_COMPILE={{cc}} $BOARD_DTS.dtb)
# and link. note: symlinked from BOARD_DTS to BOARD variable (often identical)
ln -sf $SRC.dtb $VAR/$BOARD.dtb
