#!/bin/sh
set -e

VAR="{{VAR}}"
DIST="{{DIST}}"
BOARD="{{board}}"

# nav in
cd $DIST/boot || exit

# install into DIST
cp -L $VAR/$BOARD.dtb $VAR/$BOARD.dts .
# and link a simple name: dts
ln -sfL $BOARD.dtb dtb
