# status-sysctl.sh — sysctl drift report across desired / deployed / live sources.
#
# DEPRECATED: superseded by status-sysctl.ts (Node type-stripped). This bash
# version is retained for reference; prefer the .ts twin.
#
# Generated by the gen_kernel subsystem for any playbook using KERNEL_SYSCTL.
# No shebang by design: this body is wrapped by files/_bin (shebang, env load,
# `set -euo pipefail`, shopt nullglob). Run as `./bin/status-sysctl.sh`.
#
# It compares three representations of your sysctl intent and flags desync:
#
#   --compfuzor [F]  DESIRED   values freshly compiled from the playbook JSON
#                              (what build-kernel-sysctl.sh *would* write). Source of
#                              truth and preferred key-of-record.
#                              Default F: $KERNEL_SYSCTL_JSON.
#   --system [F]     DEPLOYED  the on-disk built conf. A missing file reads as
#                              <missing> for every key — i.e. "rebuild advised"
#                              (the systemctl daemon-reload analogue). NOT an
#                              error: missing == drifted.
#                              Default F: $DIR/etc/kernel.sysctl.conf.
#   --kernel         LIVE      current values from the running kernel via
#                              `sysctl -n`. Looked up per key; never defines
#                              the key set (the kernel can't enumerate *your*
#                              intent).
#
# Output:
#   default (TSV)   header + one row per key (sorted):
#                   key <TAB> status <TAB> <one col per selected source>
#                   status is OK when all selected sources agree, DRIFT else.
#                   Absent values show as <missing>.
#   --json          machine-readable JSON: { drift, sources, keys:[...] }.
#
# Flags:
#   --json           emit JSON instead of TSV.
#   -q               quiet: print nothing; exit 0 no drift / 1 drift / 2 error.
#   -h, --help       short help.
#
# With no source flags, all three sources are compared (default = "all"), and
# the status is printed — so a bare `status-sysctl.sh` is the show-all report.
#
# The DESIRED projection mirrors build-kernel-sysctl.sh; keep the two in sync so
# DESIRED always equals what build emits.

# --- short help ------------------------------------------------------------

usage() {
  cat >&2 <<'EOF'
usage: status-sysctl.sh [--json] [-q] [--compfuzor [F]] [--system [F]] [--kernel] [-h]

Compare sysctl state across sources and report drift (TSV by default).
  --compfuzor [F]  desired: rebuilt from playbook JSON (defines keys)
  --system [F]     deployed: on-disk built conf (missing => rebuild advised)
  --kernel         live: current kernel values via `sysctl -n`
  --json           emit JSON {drift,sources,keys} instead of TSV
  -q               quiet; exit 0 in-sync / 1 drift / 2 error
  -h, --help       show this help

Defaults to all three sources. See the script header for full details.
EOF
}

die() { printf 'status-sysctl.sh: %s\n' "$*" >&2; exit 2; }

# --- defaults (from the gen_kernel environment, set via env.export) --------

json_file="${KERNEL_SYSCTL_JSON:-}"
conf_file="${DIR:-}/etc/kernel.sysctl.conf"

# --- flag parsing ----------------------------------------------------------
# --compfuzor/--system take an OPTIONAL path: consume the next token only when
# it is present and does not itself look like a flag.
out_json=0
quiet=0
want_cf=0    # compfuzor (desired, from JSON)
want_sys=0   # system    (deployed on-disk conf)
want_kr=0    # kernel    (live)

while [ "$#" -gt 0 ]; do
  case "$1" in
    -h|--help) usage; exit 0 ;;
    -q) quiet=1; shift ;;
    --json) out_json=1; shift ;;
    --compfuzor)
      want_cf=1; shift
      if [ "$#" -gt 0 ] && [ "${1#-}" = "$1" ]; then json_file="$1"; shift; fi ;;
    --system)
      want_sys=1; shift
      if [ "$#" -gt 0 ] && [ "${1#-}" = "$1" ]; then conf_file="$1"; shift; fi ;;
    --kernel) want_kr=1; shift ;;
    --) shift; break ;;
    *) die "unknown option: $1 (see --help)" ;;
  esac
done

# No source flags => compare everything and print status.
if [ "$want_cf" -eq 0 ] && [ "$want_sys" -eq 0 ] && [ "$want_kr" -eq 0 ]; then
  want_cf=1; want_sys=1; want_kr=1
fi

# The key set must come from declared intent (compfuzor or system). The live
# kernel alone cannot tell us which keys the playbook cares about.
if [ "$want_cf" -eq 0 ] && [ "$want_sys" -eq 0 ] && [ "$want_kr" -eq 1 ]; then
  die "--kernel needs --compfuzor or --system to define the key set"
fi

# --- load each selected source into an associative array -------------------
declare -A v_cf v_sys v_kr

# DESIRED: compiled straight from the JSON. Unreadable/missing is a hard
# error (source of truth). Projection matches build-kernel-sysctl.sh.
if [ "$want_cf" -eq 1 ]; then
  [ -n "$json_file" ] || die "--compfuzor needs KERNEL_SYSCTL_JSON or a FILE argument"
  [ -r "$json_file" ] || die "cannot read json: $json_file"
  while IFS=$'\t' read -r k val; do
    [ -n "$k" ] && v_cf["$k"]="$val"
  done < <(jq -r 'to_entries | sort_by(.key) | .[] | "\(.key)\t\(.value|tostring)"' "$json_file")
fi

# DEPLOYED: parse `key = value`, tolerating comments/blanks. Missing/unreadable
# file yields no entries => every key renders <missing> (the rebuild signal).
if [ "$want_sys" -eq 1 ]; then
  if [ -n "$conf_file" ] && [ -r "$conf_file" ]; then
    while IFS=$'\t' read -r k val; do
      [ -n "$k" ] && v_sys["$k"]="$val"
    done < <(awk '
      /^[[:space:]]*#/ { next }
      /^[[:space:]]*$/ { next }
      {
        line = $0
        sub(/^[[:space:]]+/, "", line)
        eq = index(line, "=")
        if (eq == 0) next
        key = substr(line, 1, eq - 1); sub(/[[:space:]]+$/, "", key)
        val = substr(line, eq + 1);    sub(/^[[:space:]]+/, "", val)
        print key "\t" val
      }
    ' "$conf_file")
  fi
fi

# --- key universe ----------------------------------------------------------
# Keys = declared intent: compfuzor (preferred) merged with system, so stale
# system-only entries still surface. Requiring data here rejects the case where
# the only key source is missing (nothing to diff against).
if [ "${#v_cf[@]}" -gt 0 ]; then
  keylist="${!v_cf[@]}"
  if [ "$want_sys" -eq 1 ]; then keylist="$keylist ${!v_sys[@]}"; fi
elif [ "${#v_sys[@]}" -gt 0 ]; then
  keylist="${!v_sys[@]}"
else
  die "no key-defining source available (need --compfuzor or --system with data)"
fi

# sorted, de-duplicated keys (sysctl dotted names contain no whitespace)
mapfile -t sorted_keys < <(printf '%s\n' $keylist | sort -u)

# LIVE: query the running kernel per key. A key the kernel doesn't expose is
# left unset => <missing>. The `if` guards sysctl's non-zero exit so `set -e`
# does not abort on an unknown key.
if [ "$want_kr" -eq 1 ]; then
  for k in "${sorted_keys[@]}"; do
    if val=$(sysctl -n "$k" 2>/dev/null); then
      v_kr["$k"]="$val"
    fi
  done
fi

# --- compute records (key, status, then one value per selected source) -----
# Each record is stored in OUTPUT order: key \t status \t v1 \t v2 ... so TSV
# prints as-is and JSON zips with column names directly. Fixed source order:
# compfuzor, system, kernel. DRIFT if any selected source differs; <missing>
# participates in equality.
order=()
[ "$want_cf" -eq 1 ]  && order+=(compfuzor)
[ "$want_sys" -eq 1 ] && order+=(system)
[ "$want_kr" -eq 1 ]  && order+=(kernel)

drift=0
records=()
for k in "${sorted_keys[@]}"; do
  status=OK
  prev=""
  first=1
  vals=()
  for src in "${order[@]}"; do
    case "$src" in
      compfuzor) v="${v_cf[$k]:-<missing>}" ;;
      system)    v="${v_sys[$k]:-<missing>}" ;;
      kernel)    v="${v_kr[$k]:-<missing>}" ;;
    esac
    vals+=("$v")
    if [ "$first" -eq 1 ]; then
      prev="$v"; first=0
    elif [ "$v" != "$prev" ]; then
      status=DRIFT
    fi
  done
  if [ "$status" = DRIFT ]; then drift=1; fi
  rec="$k"$'\t'"$status"
  for v in "${vals[@]}"; do rec="$rec"$'\t'"$v"; done
  records+=("$rec")
done

# --- quiet: exit code only -------------------------------------------------
if [ "$quiet" -eq 1 ]; then
  exit "$drift"
fi

# --- emit ------------------------------------------------------------------
if [ "$out_json" -eq 1 ]; then
  sources_json=$(printf '%s\n' "${order[@]}" | jq -R . | jq -s .)
  cols_json=$(printf '%s\n' key status "${order[@]}" | jq -R . | jq -s .)
  if [ "${#records[@]}" -gt 0 ]; then
    printf '%s\n' "${records[@]}" \
      | jq -R --argjson cols "$cols_json" --argjson sources "$sources_json" --argjson drift "$drift" '
          [ split("\t") as $row
            | reduce range(0; $cols|length) as $i ({}; .[$cols[$i]] = $row[$i]) ]
          | { drift: $drift, sources: $sources, keys: . }
        '
  else
    jq -n --argjson sources "$sources_json" --argjson drift "$drift" '{drift:$drift, sources:$sources, keys:[]}'
  fi
else
  printf 'key\tstatus'
  for src in "${order[@]}"; do printf '\t%s' "$src"; done
  printf '\n'
  [ "${#records[@]}" -gt 0 ] && printf '%s\n' "${records[@]}"
fi

exit "$drift"
